import React, { useState, useMemo } from 'react';
import { motion } from 'framer-motion';
import {
  Shield,
  ShieldAlert,
  ShieldCheck,
  Lock,
  Unlock,
  AlertTriangle,
  FileText,
  Activity,
  UserCheck,
  RefreshCw,
  AlertOctagon,
  Trash2,
  CheckCircle2,
  Info,
  AlertCircle,
  RotateCw,
  Download,
  Clock,
  Filter
} from 'lucide-react';
import {
  Button,
  Card,
  CardHeader,
  CardTitle,
  CardSubtitle,
  CardBody,
  Badge,
  ProgressBar,
  Table,
  TableRow,
  TableCell,
  EmptyState,
  CardSkeleton,
  TableSkeleton
} from '../components/ui';
import { Toast, useToast } from '../components/ui/Toast';
import useSecurityScan from '../hooks/useSecurityScan';
import { useWallet } from '../context/WalletContext';

export default function SecurityCenter() {
  const { effectiveAddress } = useWallet();
  const { stats, scanResult, loading, error, hasScanned, scanTimestamp, refresh, runScan } = useSecurityScan(effectiveAddress);
  const { showToast, ToastComponent } = useToast();
  const [severityFilter, setSeverityFilter] = useState('all');

  const handleRefresh = () => {
    refresh();
    showToast('Re-running security scan...', 'info');
  };

  // Export as JSON
  const handleExportJSON = () => {
    if (!scanResult) {
      showToast('No scan data to export', 'error');
      return;
    }
    const blob = new Blob([JSON.stringify(scanResult, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `vaultsense-security-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('Security report exported as JSON', 'success');
  };

  // Export as PDF (generates a printable HTML and opens print dialog)
  const handleExportPDF = () => {
    if (!scanResult || !stats) {
      showToast('No scan data to export', 'error');
      return;
    }
    const html = `<!DOCTYPE html><html><head><title>VaultSense Security Report</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#222;max-width:800px;margin:0 auto}
      h1{color:#7c3aed;border-bottom:2px solid #7c3aed;padding-bottom:8px}
      .score{font-size:48px;font-weight:bold;color:${stats.healthScore >= 70 ? '#10B981' : stats.healthScore >= 50 ? '#F59E0B' : '#EF4444'}}
      table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #ddd;padding:8px;text-align:left}
      th{background:#f5f5f5}.risk-high{color:#EF4444}.risk-medium{color:#F59E0B}.risk-low{color:#10B981}
      .meta{color:#666;font-size:12px;margin-top:24px}</style></head><body>
      <h1>VaultSense Security Report</h1>
      <p><strong>Wallet:</strong> ${effectiveAddress}</p>
      <p><strong>Scan Time:</strong> ${scanTimestamp?.toLocaleString() || 'N/A'}</p>
      <div class="score">${stats.healthScore}/100</div>
      <p><strong>Status:</strong> ${stats.overallStatus} | <strong>Risks:</strong> ${stats.totalRisks || 0} | <strong>Tokens Scanned:</strong> ${stats.scannedTokens || 0}</p>
      ${stats.riskDetections?.length > 0 ? `<h2>Risk Detections</h2><table><tr><th>Token</th><th>Severity</th><th>Issue</th><th>Chain</th></tr>
        ${stats.riskDetections.map((r) => `<tr><td>${r.token}</td><td class="risk-${r.riskLevel?.toLowerCase()}">${r.riskLevel}</td><td>${r.issue}</td><td>${r.chain}</td></tr>`).join('')}</table>` : ''}
      ${stats.recommendations?.length > 0 ? `<h2>Recommendations</h2><ul>${stats.recommendations.map((r) => `<li>${typeof r === 'string' ? r : r.text}</li>`).join('')}</ul>` : ''}
      <p class="meta">Generated by VaultSense · ${new Date().toLocaleString()}</p>
    </body></html>`;
    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.print();
    showToast('PDF report opened in new window', 'success');
  };

  // ── Error State ─────────────────────────────────────────────────────────────
  if (error && !loading && !hasScanned) {
    return (
      <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="space-y-8 pb-12">
        {ToastComponent}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-white/5 pb-6">
          <div className="space-y-1">
            <h1 className="text-3xl font-extrabold tracking-tight text-text">Security Center</h1>
            <p className="text-sm text-gray-400">Analyze wallet health, detect risks, and monitor smart contract approvals.</p>
          </div>
        </div>
        <EmptyState
          icon={AlertCircle}
          title="Security Scan Failed"
          description={error}
          action={<Button variant="primary" leftIcon={RotateCw} onClick={handleRefresh}>Retry Scan</Button>}
        />
      </motion.div>
    );
  }

  // Use stats from hook, or empty defaults
  const overviewData = stats || {
    overallStatus: 'SCANNING',
    healthScore: 0,
    riskSummaryCards: [],
    healthBreakdown: [],
    riskDetections: [],
    dangerousWatchlist: [],
    recommendations: [],
  };

  // Filter risk detections by severity
  const filteredRisks = useMemo(() => {
    if (severityFilter === 'all') return overviewData.riskDetections || [];
    return (overviewData.riskDetections || []).filter((r) =>
      (r.riskLevel || '').toLowerCase() === severityFilter.toLowerCase()
    );
  }, [overviewData.riskDetections, severityFilter]);

  return (
    <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="space-y-8 pb-12">
      {ToastComponent}

      {/* SECTION 1: Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-white/5 pb-6">
        <div className="space-y-1">
          <h1 className="text-3xl font-extrabold tracking-tight text-text">Security Center</h1>
          <p className="text-sm text-gray-400">Analyze wallet health, detect risks, and monitor smart contract approvals.</p>
        </div>
        <div className="flex items-center gap-3 shrink-0 flex-wrap">
          {scanTimestamp && (
            <div className="hidden sm:flex items-center gap-1.5 px-3 py-2 bg-white/5 border border-white/5 rounded-xl text-[11px] text-gray-400">
              <Clock className="h-3.5 w-3.5 text-primary" />
              <span>Scanned: {scanTimestamp.toLocaleTimeString()}</span>
            </div>
          )}
          <Button variant="outline" size="sm" leftIcon={Download} className="flex items-center gap-2 px-3 py-2.5 h-10 rounded-xl text-xs" onClick={handleExportJSON} disabled={!hasScanned}>
            JSON
          </Button>
          <Button variant="outline" size="sm" leftIcon={FileText} className="flex items-center gap-2 px-3 py-2.5 h-10 rounded-xl text-xs" onClick={handleExportPDF} disabled={!hasScanned}>
            PDF
          </Button>
          <Button variant="primary" size="sm" leftIcon={RefreshCw} className="flex items-center gap-2 px-4 py-2.5 h-10 rounded-xl" onClick={handleRefresh} loading={loading}>
            <span>{loading ? 'Scanning...' : hasScanned ? 'Rescan' : 'Run Scanner'}</span>
          </Button>
        </div>
      </div>

      {/* SECTION 2: Security Overview Hero & Breakdown Row */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Overview hero dial card (8 columns) */}
        <div className="col-span-1 lg:col-span-8">
          <Card hover className="h-full bg-gradient-to-br from-[#111118] via-[#0b1c15] to-[#111118] border border-success/20">
            <CardBody className="p-6 sm:p-8 flex flex-col sm:flex-row items-center justify-between gap-8">
              <div className="space-y-4 text-center sm:text-left">
                <div className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wider ${
                  overviewData.overallStatus === 'SAFE' || overviewData.overallStatus === 'Excellent' || overviewData.overallStatus === 'GOOD'
                    ? 'bg-success/15 border border-success/20 text-success'
                    : overviewData.overallStatus === 'WARNING'
                    ? 'bg-amber-500/15 border border-amber-500/20 text-amber-500'
                    : 'bg-danger/15 border border-danger/20 text-danger'
                }`}>
                  <Shield className="h-3.5 w-3.5" />
                  <span>Overall Status: {overviewData.overallStatus}</span>
                </div>
                <h3 className="text-xl sm:text-2xl font-black text-text">
                  {loading ? 'Running security analysis...' : 'Wallet shielding is fully active'}
                </h3>
                <p className="text-sm text-gray-400 max-w-md leading-relaxed">
                  {overviewData.summary || 'No malicious threats or signature drainers have access to your holdings. Run scanner weekly to ensure continued safety.'}
                </p>
                <div className="grid grid-cols-2 gap-4 max-w-xs mx-auto sm:mx-0 pt-2">
                  <div className="p-3 bg-white/5 border border-white/5 rounded-2xl">
                    <p className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">Health Score</p>
                    <p className="text-xs font-bold text-text mt-0.5">{overviewData.healthScore}/100</p>
                  </div>
                  <div className="p-3 bg-white/5 border border-white/5 rounded-2xl">
                    <p className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">Risks Found</p>
                    <p className="text-xs font-bold text-text mt-0.5">{overviewData.totalRisks || 0}</p>
                  </div>
                </div>
              </div>
              {/* SVG Circular Dial */}
              <div className="relative flex items-center justify-center shrink-0">
                <svg height={140} width={140} className="rotate-[-90deg]">
                  <circle stroke="rgba(255, 255, 255, 0.03)" fill="transparent" strokeWidth={10} r={55} cx={70} cy={70} />
                  <circle
                    stroke={overviewData.healthScore >= 70 ? '#10B981' : overviewData.healthScore >= 50 ? '#F59E0B' : '#EF4444'}
                    fill="transparent"
                    strokeWidth={10}
                    strokeDasharray={2 * Math.PI * 55}
                    style={{ strokeDashoffset: (2 * Math.PI * 55) - (overviewData.healthScore / 100) * (2 * Math.PI * 55) }}
                    strokeLinecap="round"
                    r={55}
                    cx={70}
                    cy={70}
                  />
                </svg>
                <div className="absolute text-center">
                  <p className="text-3xl font-black text-text leading-none">{loading ? '--' : overviewData.healthScore}</p>
                  <p className="text-[9px] text-gray-500 font-bold uppercase tracking-widest mt-1">Health Score</p>
                </div>
              </div>
            </CardBody>
          </Card>
        </div>

        {/* Health breakdown (4 columns) */}
        <div className="col-span-1 lg:col-span-4">
          <Card hover className="h-full border border-white/5 hover:border-primary/20">
            <CardHeader className="pb-4">
              <div>
                <CardTitle>Health breakdown</CardTitle>
                <CardSubtitle>Vulnerability indices by vector</CardSubtitle>
              </div>
              <Activity className="h-5 w-5 text-primary" />
            </CardHeader>
            <CardBody className="space-y-4">
              {loading ? (
                <div className="space-y-4">
                  {[1, 2, 3, 4].map((i) => <div key={i} className="h-8 bg-white/5 rounded-xl skeleton-pulse" />)}
                </div>
              ) : overviewData.healthBreakdown?.length > 0 ? (
                overviewData.healthBreakdown.map((item) => (
                  <div key={item.name} className="space-y-2">
                    <div className="flex justify-between items-center text-xs">
                      <span className="text-gray-400 font-semibold">{item.name}</span>
                      <span className="text-text font-bold">{item.percentage}%</span>
                    </div>
                    <ProgressBar value={item.percentage} variant={item.variant || (item.percentage >= 80 ? 'success' : item.percentage >= 60 ? 'warning' : 'danger')} animated />
                  </div>
                ))
              ) : (
                <p className="text-sm text-gray-500 text-center py-4">No breakdown data</p>
              )}
            </CardBody>
          </Card>
        </div>
      </div>

      {/* SECTION 3: Risk Summary Cards */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {[1, 2, 3, 4].map((i) => <CardSkeleton key={i} />)}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {overviewData.riskSummaryCards?.map((card) => {
            const iconMap = { 'safe-assets': ShieldCheck, 'medium-risk': AlertTriangle, 'high-risk': ShieldAlert, 'active-approvals': Unlock, 'tokens-scanned': FileText };
            const Icon = iconMap[card.id] || Shield;
            return (
              <Card key={card.id} hover className="border border-white/5 hover:border-primary/20 flex flex-col justify-between">
                <CardHeader className="flex items-center justify-between pb-3">
                  <CardTitle className="text-xs font-semibold uppercase tracking-wider text-gray-500">{card.title}</CardTitle>
                  <div className={`p-2 rounded-xl border bg-white/5 border-white/5 ${card.color}`}>
                    <Icon className="h-4 w-4" />
                  </div>
                </CardHeader>
                <CardBody className="space-y-1">
                  <h3 className="text-2xl font-black tracking-tight text-text">{card.value}</h3>
                  <p className="text-[11px] text-gray-500 font-medium">{card.desc}</p>
                </CardBody>
              </Card>
            );
          })}
        </div>
      )}

      {/* Two-Column main section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">

        {/* SECTION 5: Risk Detection Table (8 columns) */}
        <div className="col-span-1 lg:col-span-8 space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div className="text-sm font-bold text-gray-400 uppercase tracking-widest">Risk Detections Log</div>
            <div className="flex items-center gap-2">
              <Filter className="h-3.5 w-3.5 text-gray-500" />
              <select
                value={severityFilter}
                onChange={(e) => setSeverityFilter(e.target.value)}
                className="bg-[#111118] border border-white/5 text-xs rounded-xl px-3 py-2 outline-none focus:border-primary/50 text-text cursor-pointer transition-colors"
              >
                <option value="all">All Severities</option>
                <option value="high">High</option>
                <option value="medium">Medium</option>
                <option value="low">Low</option>
              </select>
            </div>
          </div>
          {loading ? (
            <TableSkeleton rows={4} cols={5} />
          ) : (
            <Table
              headers={['Token', 'Risk Level', 'Vulnerability Issue', 'Chain', 'Status']}
              isEmpty={filteredRisks.length === 0}
              emptyStateComponent={
                <EmptyState
                  icon={ShieldCheck}
                  title={severityFilter === 'all' ? 'No risks detected' : `No ${severityFilter} risks`}
                  description={severityFilter === 'all' ? 'All scanned tokens appear safe. Run a new scan to check for emerging threats.' : `No ${severityFilter} severity risks found. Try a different filter.`}
                />
              }
            >
              {filteredRisks.map((item, idx) => (
                <TableRow key={idx}>
                  <TableCell className="font-semibold text-text text-sm">{item.token}</TableCell>
                  <TableCell>
                    <Badge variant={item.riskVariant} className="text-[9px] px-2 py-0.5 font-bold uppercase tracking-wider">
                      {item.riskLevel}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-xs text-gray-400 max-w-[180px] truncate">{item.issue}</TableCell>
                  <TableCell>
                    <Badge variant="info" className="text-[10px]">{item.chain}</Badge>
                  </TableCell>
                  <TableCell>
                    <Badge variant={item.statusVariant} className="text-[10px]">{item.status}</Badge>
                  </TableCell>
                </TableRow>
              ))}
            </Table>
          )}
        </div>

        {/* SECTION 6: Dangerous Token Watchlist (4 columns) */}
        <div className="col-span-1 lg:col-span-4 space-y-4">
          <div className="text-sm font-bold text-gray-400 uppercase tracking-widest">Dangerous Token Watchlist</div>
          {loading ? (
            <div className="space-y-4">
              {[1, 2].map((i) => <div key={i} className="h-28 bg-white/5 rounded-2xl skeleton-pulse" />)}
            </div>
          ) : overviewData.dangerousWatchlist?.length > 0 ? (
            <div className="space-y-4">
              {overviewData.dangerousWatchlist.map((item, idx) => (
                <Card key={idx} hover className="border border-danger/20 bg-danger/[0.01]">
                  <CardBody className="p-5 space-y-3.5">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <AlertOctagon className="h-4 w-4 text-danger" />
                        <span className="font-extrabold text-sm text-text">{item.tokenName}</span>
                      </div>
                      <Badge variant={item.riskVariant} className="text-[9px] font-bold px-1.5 py-0">{item.riskLevel}</Badge>
                    </div>
                    <p className="text-xs text-gray-400 leading-relaxed">{item.description}</p>
                  </CardBody>
                </Card>
              ))}
            </div>
          ) : (
            <EmptyState icon={ShieldCheck} title="No dangerous tokens" description="No high-risk tokens detected in your portfolio." />
          )}
        </div>

        {/* SECTION 8: Security Recommendations (4 columns) */}
        <div className="col-span-1 lg:col-span-4 space-y-4">
          <div className="text-sm font-bold text-gray-400 uppercase tracking-widest">Security Recommendations</div>
          <Card hover className="border border-white/5 hover:border-primary/20">
            <CardBody className="p-6 space-y-4.5">
              {loading ? (
                <div className="space-y-4">
                  {[1, 2, 3].map((i) => <div key={i} className="h-6 bg-white/5 rounded-xl skeleton-pulse" />)}
                </div>
              ) : overviewData.recommendations?.length > 0 ? (
                overviewData.recommendations.map((rec, idx) => (
                  <div key={idx} className="flex items-start gap-3 text-xs sm:text-sm">
                    <div className="h-5 w-5 rounded-full bg-primary/10 border border-primary/10 flex items-center justify-center text-primary shrink-0 mt-0.5">
                      <UserCheck className="h-3 w-3" />
                    </div>
                    <span className="text-gray-300 font-medium leading-relaxed mt-0.5">{typeof rec === 'string' ? rec : rec.text || rec}</span>
                  </div>
                ))
              ) : (
                <p className="text-sm text-gray-500 text-center py-4">No recommendations</p>
              )}
            </CardBody>
          </Card>
        </div>
      </div>
    </motion.div>
  );
}
